//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adan.Client.Plugins.StuffDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adan.Client.Plugins.StuffDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Envenom: [{0}].
        /// </summary>
        internal static string AffectEnvenom {
            get {
                return ResourceManager.GetString("AffectEnvenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на magic arrows: extra damage by {0} magic {1}d{2} [{3}].
        /// </summary>
        internal static string AffectMagicArrows {
            get {
                return ResourceManager.GetString("AffectMagicArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на air.
        /// </summary>
        internal static string AffectMagicArrowsAir {
            get {
                return ResourceManager.GetString("AffectMagicArrowsAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на earth.
        /// </summary>
        internal static string AffectMagicArrowsEarth {
            get {
                return ResourceManager.GetString("AffectMagicArrowsEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на fire.
        /// </summary>
        internal static string AffectMagicArrowsFire {
            get {
                return ResourceManager.GetString("AffectMagicArrowsFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на magic arrows: extra datage by {0} magic {1}d{2}.
        /// </summary>
        internal static string AffectMagicArrowsUnlimited {
            get {
                return ResourceManager.GetString("AffectMagicArrowsUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на water.
        /// </summary>
        internal static string AffectMagicArrowsWater {
            get {
                return ResourceManager.GetString("AffectMagicArrowsWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Affects.
        /// </summary>
        internal static string Affects {
            get {
                return ResourceManager.GetString("Affects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applied affects:.
        /// </summary>
        internal static string AppliedAffects {
            get {
                return ResourceManager.GetString("AppliedAffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Armor: {0}.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Armor class(AC): {0}.
        /// </summary>
        internal static string ArmorClass {
            get {
                return ResourceManager.GetString("ArmorClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can be weared.
        /// </summary>
        internal static string CanBeWeared {
            get {
                return ResourceManager.GetString("CanBeWeared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments: {0}.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight: {0:F0}, Price: {1}, Rent: {2}({3}), Timer: {4}, Offline Timer: {5}, Material: {6}.
        /// </summary>
        internal static string CommonStats {
            get {
                return ResourceManager.GetString("CommonStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum level: {0}.
        /// </summary>
        internal static string CraftBookMinLevel {
            get {
                return ResourceManager.GetString("CraftBookMinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum skill level: {0}%.
        /// </summary>
        internal static string CraftBookMinSkillLevel {
            get {
                return ResourceManager.GetString("CraftBookMinSkillLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description: {0}.
        /// </summary>
        internal static string CraftBookRecipeDescription {
            get {
                return ResourceManager.GetString("CraftBookRecipeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recipe: {0}.
        /// </summary>
        internal static string CraftBookRecipeName {
            get {
                return ResourceManager.GetString("CraftBookRecipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color: {0}.
        /// </summary>
        internal static string IngredientColor {
            get {
                return ResourceManager.GetString("IngredientColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power: {0}.
        /// </summary>
        internal static string IngredientPower {
            get {
                return ResourceManager.GetString("IngredientPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} d. {1} h..
        /// </summary>
        internal static string LongTimeFormat {
            get {
                return ResourceManager.GetString("LongTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lore.
        /// </summary>
        internal static string LoreCommand {
            get {
                return ResourceManager.GetString("LoreCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lorec.
        /// </summary>
        internal static string LoreCommentCommand {
            get {
                return ResourceManager.GetString("LoreCommentCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not add comments to object description. Find required object first. .
        /// </summary>
        internal static string LoreCommentError {
            get {
                return ResourceManager.GetString("LoreCommentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use &apos;lorec &lt;comment&gt;&apos; to add comments for latest object description..
        /// </summary>
        internal static string LoreCommentsHelp {
            get {
                return ResourceManager.GetString("LoreCommentsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Descrption of object &apos;{0}&apos; was saved to database..
        /// </summary>
        internal static string LoreCreated {
            get {
                return ResourceManager.GetString("LoreCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found object &apos;{0}&apos;:.
        /// </summary>
        internal static string LoreFoundObject {
            get {
                return ResourceManager.GetString("LoreFoundObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User &apos;lorehelp&apos; command to get help about stuff database..
        /// </summary>
        internal static string LoreGetHelp {
            get {
                return ResourceManager.GetString("LoreGetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use &apos;lore &lt;item_name&gt;&apos; command to get saved object description..
        /// </summary>
        internal static string LoreHelp {
            get {
                return ResourceManager.GetString("LoreHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lorehelp.
        /// </summary>
        internal static string LoreHelpCommand {
            get {
                return ResourceManager.GetString("LoreHelpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nothing found..
        /// </summary>
        internal static string LoreNothingFound {
            get {
                return ResourceManager.GetString("LoreNothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your query produced too much results. Please use more specific search..
        /// </summary>
        internal static string LoreTooMuchFound {
            get {
                return ResourceManager.GetString("LoreTooMuchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Descrption of object &apos;{0}&apos; was updated in database..
        /// </summary>
        internal static string LoreUpdated {
            get {
                return ResourceManager.GetString("LoreUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum level required: {0}.
        /// </summary>
        internal static string MinLevel {
            get {
                return ResourceManager.GetString("MinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No flags.
        /// </summary>
        internal static string NoFlags {
            get {
                return ResourceManager.GetString("NoFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object affects.
        /// </summary>
        internal static string ObjectAffects {
            get {
                return ResourceManager.GetString("ObjectAffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object flags.
        /// </summary>
        internal static string ObjectFlags {
            get {
                return ResourceManager.GetString("ObjectFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object type.
        /// </summary>
        internal static string ObjectType {
            get {
                return ResourceManager.GetString("ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restriction flags.
        /// </summary>
        internal static string RestrictionFlags {
            get {
                return ResourceManager.GetString("RestrictionFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} h..
        /// </summary>
        internal static string ShortTimeFormat {
            get {
                return ResourceManager.GetString("ShortTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:+#;-#;#} to skill/spell &apos;{1}&apos;.
        /// </summary>
        internal static string SkillEnhance {
            get {
                return ResourceManager.GetString("SkillEnhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resist to skill/spell &apos;{0}&apos; {1}%.
        /// </summary>
        internal static string SkillResist {
            get {
                return ResourceManager.GetString("SkillResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spell: {0}.
        /// </summary>
        internal static string SpellBookSpell {
            get {
                return ResourceManager.GetString("SpellBookSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cast count: {0}.
        /// </summary>
        internal static string SpellCastCount {
            get {
                return ResourceManager.GetString("SpellCastCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Infinite.
        /// </summary>
        internal static string SpellCastCountInfinity {
            get {
                return ResourceManager.GetString("SpellCastCountInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum level: {0}.
        /// </summary>
        internal static string SpellMinLevel {
            get {
                return ResourceManager.GetString("SpellMinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Required profession: {0}.
        /// </summary>
        internal static string SpellProfession {
            get {
                return ResourceManager.GetString("SpellProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spells.
        /// </summary>
        internal static string Spells {
            get {
                return ResourceManager.GetString("Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum {0} charges, {1} charges left..
        /// </summary>
        internal static string StaffCharges {
            get {
                return ResourceManager.GetString("StaffCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weapon power &apos;{0}d{1}&apos;, average {2:F1}..
        /// </summary>
        internal static string WeaponPower {
            get {
                return ResourceManager.GetString("WeaponPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Required skill: &apos;{0}&apos;..
        /// </summary>
        internal static string WeaponSkill {
            get {
                return ResourceManager.GetString("WeaponSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string WearABOUT {
            get {
                return ResourceManager.GetString("WearABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arms.
        /// </summary>
        internal static string WearARMS {
            get {
                return ResourceManager.GetString("WearARMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body.
        /// </summary>
        internal static string WearBody {
            get {
                return ResourceManager.GetString("WearBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Def1.
        /// </summary>
        internal static string WearDEF1 {
            get {
                return ResourceManager.GetString("WearDEF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Def2.
        /// </summary>
        internal static string WearDEF2 {
            get {
                return ResourceManager.GetString("WearDEF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Def3.
        /// </summary>
        internal static string WearDef3 {
            get {
                return ResourceManager.GetString("WearDef3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wield both hands.
        /// </summary>
        internal static string WearDWIELD {
            get {
                return ResourceManager.GetString("WearDWIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ears.
        /// </summary>
        internal static string WearEARS {
            get {
                return ResourceManager.GetString("WearEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Eyes.
        /// </summary>
        internal static string WearEYES {
            get {
                return ResourceManager.GetString("WearEYES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feet.
        /// </summary>
        internal static string WearFEET {
            get {
                return ResourceManager.GetString("WearFEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finger.
        /// </summary>
        internal static string WearFINGER {
            get {
                return ResourceManager.GetString("WearFINGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hands.
        /// </summary>
        internal static string WearHANDS {
            get {
                return ResourceManager.GetString("WearHANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Head.
        /// </summary>
        internal static string WearHEAD {
            get {
                return ResourceManager.GetString("WearHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hold.
        /// </summary>
        internal static string WearHOLD {
            get {
                return ResourceManager.GetString("WearHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wearing affect: {0}, Level: {1}, Timeout: {2}.
        /// </summary>
        internal static string WearingAffect {
            get {
                return ResourceManager.GetString("WearingAffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Legs.
        /// </summary>
        internal static string WearLEGS {
            get {
                return ResourceManager.GetString("WearLEGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Neck.
        /// </summary>
        internal static string WearNECK {
            get {
                return ResourceManager.GetString("WearNECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shield.
        /// </summary>
        internal static string WearSHIELD {
            get {
                return ResourceManager.GetString("WearSHIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waist.
        /// </summary>
        internal static string WearWAIST {
            get {
                return ResourceManager.GetString("WearWAIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wield.
        /// </summary>
        internal static string WearWIELD {
            get {
                return ResourceManager.GetString("WearWIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrist.
        /// </summary>
        internal static string WearWRIST {
            get {
                return ResourceManager.GetString("WearWRIST", resourceCulture);
            }
        }
    }
}
