//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adan.Client.Plugins.StuffDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adan.Client.Plugins.StuffDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envenom: [{0}].
        /// </summary>
        internal static string AffectEnvenom {
            get {
                return ResourceManager.GetString("AffectEnvenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magic arrows: extra datage by {0} magic {1}d{2} [{3}].
        /// </summary>
        internal static string AffectMagicArrows {
            get {
                return ResourceManager.GetString("AffectMagicArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to air.
        /// </summary>
        internal static string AffectMagicArrowsAir {
            get {
                return ResourceManager.GetString("AffectMagicArrowsAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earth.
        /// </summary>
        internal static string AffectMagicArrowsEarth {
            get {
                return ResourceManager.GetString("AffectMagicArrowsEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fire.
        /// </summary>
        internal static string AffectMagicArrowsFire {
            get {
                return ResourceManager.GetString("AffectMagicArrowsFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magic arrows: extra datage by {0} magic {1}d{2}.
        /// </summary>
        internal static string AffectMagicArrowsUnlimited {
            get {
                return ResourceManager.GetString("AffectMagicArrowsUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to water.
        /// </summary>
        internal static string AffectMagicArrowsWater {
            get {
                return ResourceManager.GetString("AffectMagicArrowsWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affects.
        /// </summary>
        internal static string Affects {
            get {
                return ResourceManager.GetString("Affects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied affects:.
        /// </summary>
        internal static string AppliedAffects {
            get {
                return ResourceManager.GetString("AppliedAffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor: {0}.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor class(AC): {0}.
        /// </summary>
        internal static string ArmorClass {
            get {
                return ResourceManager.GetString("ArmorClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be weared.
        /// </summary>
        internal static string CanBeWeared {
            get {
                return ResourceManager.GetString("CanBeWeared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments: {0}.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight: {0:F0}, Price: {1}, Rent: {2}({3}), Timer: {4}, Material: {5}.
        /// </summary>
        internal static string CommonStats {
            get {
                return ResourceManager.GetString("CommonStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum level: {0}.
        /// </summary>
        internal static string CraftBookMinLevel {
            get {
                return ResourceManager.GetString("CraftBookMinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum skill level: {0}%.
        /// </summary>
        internal static string CraftBookMinSkillLevel {
            get {
                return ResourceManager.GetString("CraftBookMinSkillLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: {0}.
        /// </summary>
        internal static string CraftBookRecipeDescription {
            get {
                return ResourceManager.GetString("CraftBookRecipeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe: {0}.
        /// </summary>
        internal static string CraftBookRecipeName {
            get {
                return ResourceManager.GetString("CraftBookRecipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color: {0}.
        /// </summary>
        internal static string IngredientColor {
            get {
                return ResourceManager.GetString("IngredientColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power: {0}.
        /// </summary>
        internal static string IngredientPower {
            get {
                return ResourceManager.GetString("IngredientPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} d. {1} h..
        /// </summary>
        internal static string LongTimeFormat {
            get {
                return ResourceManager.GetString("LongTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lore.
        /// </summary>
        internal static string LoreCommand {
            get {
                return ResourceManager.GetString("LoreCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lorec.
        /// </summary>
        internal static string LoreCommentCommand {
            get {
                return ResourceManager.GetString("LoreCommentCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add comments to object description. Find required object first. .
        /// </summary>
        internal static string LoreCommentError {
            get {
                return ResourceManager.GetString("LoreCommentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;lorec &lt;comment&gt;&apos; to add comments for latest object description..
        /// </summary>
        internal static string LoreCommentsHelp {
            get {
                return ResourceManager.GetString("LoreCommentsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrption of object &apos;{0}&apos; was saved to database..
        /// </summary>
        internal static string LoreCreated {
            get {
                return ResourceManager.GetString("LoreCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found object &apos;{0}&apos;:.
        /// </summary>
        internal static string LoreFoundObject {
            get {
                return ResourceManager.GetString("LoreFoundObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;lorehelp&apos; command to get help about stuff database..
        /// </summary>
        internal static string LoreGetHelp {
            get {
                return ResourceManager.GetString("LoreGetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;lore &lt;item_name&gt;&apos; command to get saved object description..
        /// </summary>
        internal static string LoreHelp {
            get {
                return ResourceManager.GetString("LoreHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lorehelp.
        /// </summary>
        internal static string LoreHelpCommand {
            get {
                return ResourceManager.GetString("LoreHelpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found..
        /// </summary>
        internal static string LoreNothingFound {
            get {
                return ResourceManager.GetString("LoreNothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your query produced too much results. Please use more specific search..
        /// </summary>
        internal static string LoreTooMuchFound {
            get {
                return ResourceManager.GetString("LoreTooMuchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrption of object &apos;{0}&apos; was updated in database..
        /// </summary>
        internal static string LoreUpdated {
            get {
                return ResourceManager.GetString("LoreUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum level required: {0}.
        /// </summary>
        internal static string MinLevel {
            get {
                return ResourceManager.GetString("MinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No flags.
        /// </summary>
        internal static string NoFlags {
            get {
                return ResourceManager.GetString("NoFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object affects.
        /// </summary>
        internal static string ObjectAffects {
            get {
                return ResourceManager.GetString("ObjectAffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object flags.
        /// </summary>
        internal static string ObjectFlags {
            get {
                return ResourceManager.GetString("ObjectFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object type.
        /// </summary>
        internal static string ObjectType {
            get {
                return ResourceManager.GetString("ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restriction flags.
        /// </summary>
        internal static string RestrictionFlags {
            get {
                return ResourceManager.GetString("RestrictionFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} h..
        /// </summary>
        internal static string ShortTimeFormat {
            get {
                return ResourceManager.GetString("ShortTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:+#;-#;#} to skill/spell &apos;{1}&apos;.
        /// </summary>
        internal static string SkillEnhance {
            get {
                return ResourceManager.GetString("SkillEnhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resist to skill/spell &apos;{0}&apos; {1}%.
        /// </summary>
        internal static string SkillResist {
            get {
                return ResourceManager.GetString("SkillResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell: {0}.
        /// </summary>
        internal static string SpellBookSpell {
            get {
                return ResourceManager.GetString("SpellBookSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast count: {0}.
        /// </summary>
        internal static string SpellCastCount {
            get {
                return ResourceManager.GetString("SpellCastCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite.
        /// </summary>
        internal static string SpellCastCountInfinity {
            get {
                return ResourceManager.GetString("SpellCastCountInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum level: {0}.
        /// </summary>
        internal static string SpellMinLevel {
            get {
                return ResourceManager.GetString("SpellMinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required profession: {0}.
        /// </summary>
        internal static string SpellProfession {
            get {
                return ResourceManager.GetString("SpellProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells.
        /// </summary>
        internal static string Spells {
            get {
                return ResourceManager.GetString("Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum {0} charges, {1} charges left..
        /// </summary>
        internal static string StaffCharges {
            get {
                return ResourceManager.GetString("StaffCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon power &apos;{0}d{1}&apos;, average {2:F1}..
        /// </summary>
        internal static string WeaponPower {
            get {
                return ResourceManager.GetString("WeaponPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required skill: &apos;{0}&apos;..
        /// </summary>
        internal static string WeaponSkill {
            get {
                return ResourceManager.GetString("WeaponSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string WearABOUT {
            get {
                return ResourceManager.GetString("WearABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arms.
        /// </summary>
        internal static string WearARMS {
            get {
                return ResourceManager.GetString("WearARMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string WearBody {
            get {
                return ResourceManager.GetString("WearBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Def1.
        /// </summary>
        internal static string WearDEF1 {
            get {
                return ResourceManager.GetString("WearDEF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Def2.
        /// </summary>
        internal static string WearDEF2 {
            get {
                return ResourceManager.GetString("WearDEF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Def3.
        /// </summary>
        internal static string WearDef3 {
            get {
                return ResourceManager.GetString("WearDef3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wield both hands.
        /// </summary>
        internal static string WearDWIELD {
            get {
                return ResourceManager.GetString("WearDWIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ears.
        /// </summary>
        internal static string WearEARS {
            get {
                return ResourceManager.GetString("WearEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyes.
        /// </summary>
        internal static string WearEYES {
            get {
                return ResourceManager.GetString("WearEYES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string WearFEET {
            get {
                return ResourceManager.GetString("WearFEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger.
        /// </summary>
        internal static string WearFINGER {
            get {
                return ResourceManager.GetString("WearFINGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands.
        /// </summary>
        internal static string WearHANDS {
            get {
                return ResourceManager.GetString("WearHANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string WearHEAD {
            get {
                return ResourceManager.GetString("WearHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        internal static string WearHOLD {
            get {
                return ResourceManager.GetString("WearHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wearing affect: {0}, Level: {1}, Timeout: {2}.
        /// </summary>
        internal static string WearingAffect {
            get {
                return ResourceManager.GetString("WearingAffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        internal static string WearLEGS {
            get {
                return ResourceManager.GetString("WearLEGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        internal static string WearNECK {
            get {
                return ResourceManager.GetString("WearNECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        internal static string WearSHIELD {
            get {
                return ResourceManager.GetString("WearSHIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        internal static string WearWAIST {
            get {
                return ResourceManager.GetString("WearWAIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wield.
        /// </summary>
        internal static string WearWIELD {
            get {
                return ResourceManager.GetString("WearWIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrist.
        /// </summary>
        internal static string WearWRIST {
            get {
                return ResourceManager.GetString("WearWRIST", resourceCulture);
            }
        }
    }
}
