//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adan.Client.Plugins.GroupWidget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adan.Client.Plugins.GroupWidget.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        public static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affect:.
        /// </summary>
        public static string Affect {
            get {
                return ResourceManager.GetString("Affect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmorCurse.
        /// </summary>
        public static string ArmorCurse {
            get {
                return ResourceManager.GetString("ArmorCurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available affects:.
        /// </summary>
        public static string AvailableAffects {
            get {
                return ResourceManager.GetString("AvailableAffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessing.
        /// </summary>
        public static string Blessing {
            get {
                return ResourceManager.GetString("Blessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blindness.
        /// </summary>
        public static string Blindness {
            get {
                return ResourceManager.GetString("Blindness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curse.
        /// </summary>
        public static string Curse {
            get {
                return ResourceManager.GetString("Curse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease.
        /// </summary>
        public static string Disease {
            get {
                return ResourceManager.GetString("Disease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed affects:.
        /// </summary>
        public static string DisplayedAffects {
            get {
                return ResourceManager.GetString("DisplayedAffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntsPower.
        /// </summary>
        public static string EntsPower {
            get {
                return ResourceManager.GetString("EntsPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fear.
        /// </summary>
        public static string Fear {
            get {
                return ResourceManager.GetString("Fear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        public static string Flight {
            get {
                return ResourceManager.GetString("Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh.
        /// </summary>
        public static string Fresh {
            get {
                return ResourceManager.GetString("Fresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group widget options.
        /// </summary>
        public static string GroupWidgetOptions {
            get {
                return ResourceManager.GetString("GroupWidgetOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healings.
        /// </summary>
        public static string Healings {
            get {
                return ResourceManager.GetString("Healings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisibility.
        /// </summary>
        public static string Invisibility {
            get {
                return ResourceManager.GetString("Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralysis.
        /// </summary>
        public static string Paralysis {
            get {
                return ResourceManager.GetString("Paralysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison.
        /// </summary>
        public static string Poison {
            get {
                return ResourceManager.GetString("Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection.
        /// </summary>
        public static string Protection {
            get {
                return ResourceManager.GetString("Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewals.
        /// </summary>
        public static string Renewals {
            get {
                return ResourceManager.GetString("Renewals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shock.
        /// </summary>
        public static string Shock {
            get {
                return ResourceManager.GetString("Shock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silence.
        /// </summary>
        public static string Silence {
            get {
                return ResourceManager.GetString("Silence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slowness.
        /// </summary>
        public static string Slowness {
            get {
                return ResourceManager.GetString("Slowness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoneCurse.
        /// </summary>
        public static string StoneCurse {
            get {
                return ResourceManager.GetString("StoneCurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stun.
        /// </summary>
        public static string Stun {
            get {
                return ResourceManager.GetString("Stun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weakness.
        /// </summary>
        public static string Weakness {
            get {
                return ResourceManager.GetString("Weakness", resourceCulture);
            }
        }
    }
}
