//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adan.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adan.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already connected..
        /// </summary>
        internal static string AlreadyConnected {
            get {
                return ResourceManager.GetString("AlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection established..
        /// </summary>
        internal static string ConnectionEstablished {
            get {
                return ResourceManager.GetString("ConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost..
        /// </summary>
        internal static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes recieved: {0}, Bytes decompressed: {1}, Compression ratio: {2:0.0}%..
        /// </summary>
        internal static string ConnectionStatistic {
            get {
                return ResourceManager.GetString("ConnectionStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging started. Log name: &apos;{0}&apos;..
        /// </summary>
        internal static string LoggingStarted {
            get {
                return ResourceManager.GetString("LoggingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging stopped..
        /// </summary>
        internal static string LoggingStopped {
            get {
                return ResourceManager.GetString("LoggingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log name can not be empty..
        /// </summary>
        internal static string LogNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("LogNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected..
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected. Please connect first..
        /// </summary>
        internal static string NotConnectedPleaseConnectFirst {
            get {
                return ResourceManager.GetString("NotConnectedPleaseConnectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client is outdated. Please download latest version at http://mudclient.codeplex.com.
        /// </summary>
        internal static string ProtocolVersionMismatch {
            get {
                return ResourceManager.GetString("ProtocolVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to connect. host - {0}; port - {1}.
        /// </summary>
        internal static string TryingToConnect {
            get {
                return ResourceManager.GetString("TryingToConnect", resourceCulture);
            }
        }
    }
}
