//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adan.Client.Map.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adan.Client.Map.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to this room.
        /// </summary>
        public static string GotoThisRoom {
            get {
                return ResourceManager.GetString("GotoThisRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road map.
        /// </summary>
        public static string RoadMap {
            get {
                return ResourceManager.GetString("RoadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions to execute on room entry:.
        /// </summary>
        public static string RoomActions {
            get {
                return ResourceManager.GetString("RoomActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias:.
        /// </summary>
        public static string RoomAlias {
            get {
                return ResourceManager.GetString("RoomAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string RoomColor {
            get {
                return ResourceManager.GetString("RoomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string RoomColorContext {
            get {
                return ResourceManager.GetString("RoomColorContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        public static string RoomComments {
            get {
                return ResourceManager.GetString("RoomComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room editor.
        /// </summary>
        public static string RoomEditor {
            get {
                return ResourceManager.GetString("RoomEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon:.
        /// </summary>
        public static string RoomIcon {
            get {
                return ResourceManager.GetString("RoomIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string RoomIconContext {
            get {
                return ResourceManager.GetString("RoomIconContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error navigating to specified room..
        /// </summary>
        public static string RoomNavigationError {
            get {
                return ResourceManager.GetString("RoomNavigationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route from &apos;{0}&apos; to &apos;{1}&apos; already exists. Overwrite?.
        /// </summary>
        public static string RouteAlreadyExistsQuestion {
            get {
                return ResourceManager.GetString("RouteAlreadyExistsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route already exists..
        /// </summary>
        public static string RouteAlreadyExistsTitle {
            get {
                return ResourceManager.GetString("RouteAlreadyExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string RouteCommandCancelRecording {
            get {
                return ResourceManager.GetString("RouteCommandCancelRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goto.
        /// </summary>
        public static string RouteCommandGoto {
            get {
                return ResourceManager.GetString("RouteCommandGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string RouteCommandHelp {
            get {
                return ResourceManager.GetString("RouteCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route.
        /// </summary>
        public static string RouteCommandPrefix {
            get {
                return ResourceManager.GetString("RouteCommandPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string RouteCommandStartRecording {
            get {
                return ResourceManager.GetString("RouteCommandStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string RouteCommandStop {
            get {
                return ResourceManager.GetString("RouteCommandStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stoprecording.
        /// </summary>
        public static string RouteCommandStopRecording {
            get {
                return ResourceManager.GetString("RouteCommandStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route from &apos;{0}&apos; to &apos;{1}&apos; deleted..
        /// </summary>
        public static string RouteDeletedMessage {
            get {
                return ResourceManager.GetString("RouteDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a route to delete:.
        /// </summary>
        public static string RouteDeleteSelect {
            get {
                return ResourceManager.GetString("RouteDeleteSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route delete..
        /// </summary>
        public static string RouteDeleteTitle {
            get {
                return ResourceManager.GetString("RouteDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination to go to:.
        /// </summary>
        public static string RouteDestinationSelect {
            get {
                return ResourceManager.GetString("RouteDestinationSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination..
        /// </summary>
        public static string RouteDestinationSelectTitle {
            get {
                return ResourceManager.GetString("RouteDestinationSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of groupmates has lost or too tired..
        /// </summary>
        public static string RouteGroupMateLostOrTired {
            get {
                return ResourceManager.GetString("RouteGroupMateLostOrTired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;route cancel&quot; - stops recording current route without saving it..
        /// </summary>
        public static string RouteHelpCancelRecording {
            get {
                return ResourceManager.GetString("RouteHelpCancelRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;goto &lt;room alias|room name&gt;&quot; - navigates to the room with specified alias/name inside current zone..
        /// </summary>
        public static string RouteHelpGoto {
            get {
                return ResourceManager.GetString("RouteHelpGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;route help&quot; - display this help..
        /// </summary>
        public static string RouteHelpHelp {
            get {
                return ResourceManager.GetString("RouteHelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;route goto &lt;point name&gt;&quot; - starts routing to specified point..
        /// </summary>
        public static string RouteHelpRoute {
            get {
                return ResourceManager.GetString("RouteHelpRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;route start &lt;start point name&gt;&quot; - start recording new route..
        /// </summary>
        public static string RouteHelpStartRecording {
            get {
                return ResourceManager.GetString("RouteHelpStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;route stoprecording &lt;end point name&gt;&quot; - stops recording current route..
        /// </summary>
        public static string RouteHelpStopRecording {
            get {
                return ResourceManager.GetString("RouteHelpStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;route stop&quot; - stops routing current route..
        /// </summary>
        public static string RouteHelpStopRoute {
            get {
                return ResourceManager.GetString("RouteHelpStopRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route point name.
        /// </summary>
        public static string RoutePointName {
            get {
                return ResourceManager.GetString("RoutePointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route point name:.
        /// </summary>
        public static string RoutePointNameEnter {
            get {
                return ResourceManager.GetString("RoutePointNameEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route point with name &apos;{0}&apos; already exists..
        /// </summary>
        public static string RoutePointNameNotUnique {
            get {
                return ResourceManager.GetString("RoutePointNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route recording canceled..
        /// </summary>
        public static string RouteRecordingCanceled {
            get {
                return ResourceManager.GetString("RouteRecordingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started recording a route from {0}..
        /// </summary>
        public static string RouteRecordingStarted {
            get {
                return ResourceManager.GetString("RouteRecordingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route from &apos;{0}&apos; to &apos;{1}&apos; created..
        /// </summary>
        public static string RouteRecordingStopped {
            get {
                return ResourceManager.GetString("RouteRecordingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available routes from current root..
        /// </summary>
        public static string RoutesAreNotAvailable {
            get {
                return ResourceManager.GetString("RoutesAreNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RoutesCancel {
            get {
                return ResourceManager.GetString("RoutesCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel recording current route.
        /// </summary>
        public static string RoutesCancelRecording {
            get {
                return ResourceManager.GetString("RoutesCancelRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto.
        /// </summary>
        public static string RoutesChoose {
            get {
                return ResourceManager.GetString("RoutesChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new route.
        /// </summary>
        public static string RoutesCreate {
            get {
                return ResourceManager.GetString("RoutesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a route.
        /// </summary>
        public static string RoutesDelete {
            get {
                return ResourceManager.GetString("RoutesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print help.
        /// </summary>
        public static string RoutesHelp {
            get {
                return ResourceManager.GetString("RoutesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified room does not exists..
        /// </summary>
        public static string RouteSpecifiedRoomDoesNotExists {
            get {
                return ResourceManager.GetString("RouteSpecifiedRoomDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop current route.
        /// </summary>
        public static string RoutesStop {
            get {
                return ResourceManager.GetString("RoutesStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording current route.
        /// </summary>
        public static string RoutesStopRecording {
            get {
                return ResourceManager.GetString("RoutesStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing to &apos;{0}&apos;..
        /// </summary>
        public static string RouteStarted {
            get {
                return ResourceManager.GetString("RouteStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route start name can not be empty..
        /// </summary>
        public static string RouteStartNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("RouteStartNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing stopped..
        /// </summary>
        public static string RouteStopped {
            get {
                return ResourceManager.GetString("RouteStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing to &apos;{0}&apos; completed..
        /// </summary>
        public static string RouteTargetAchieved {
            get {
                return ResourceManager.GetString("RouteTargetAchieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target with name &apos;{0}&apos; is not available from current room..
        /// </summary>
        public static string RouteTargetIsNotAvailable {
            get {
                return ResourceManager.GetString("RouteTargetIsNotAvailable", resourceCulture);
            }
        }
    }
}
